version: "1.0"

stages:
  - default

steps:
  configure_deployment_vars:
    title: Configure shared deployment variables
    image: alpine:latest
    commands:
      - cf_export HELMREPO=platform

  spinnake_deps:
    image: harbor.tools.gladly.com/pipelines/gladly-pipeline-step-helm
    title: Build Spinnaker dependencies
    working_directory: ${{main_clone}}/stable/spinnaker/
    commands:
      - helm dependency build
    when:
      branch:
        only:
          - gladly-release

  spinnaker:
    image: harbor.tools.gladly.com/pipelines/gladly-pipeline-step-helm
    title: Helm Package
    working_directory: ${{main_clone}}/stable/spinnaker/
    environment:
      - ACTION=package
    when:
      branch:
        only:
          - gladly-release
